"""Neighborhoods used to sweep Bengaluru for ingestion (Text Search has no
practical way to enumerate a whole city in one call, so we query per-area
and dedup by place_id instead)."""

BLR_NEIGHBORHOODS = [
    "Indiranagar",
    "Koramangala",
    "HSR Layout",
    "BTM Layout",
    "JP Nagar",
    "Jayanagar",
    "Basavanagudi",
    "Malleshwaram",
    "Rajajinagar",
    "Vijayanagar",
    "Banashankari",
    "Rajarajeshwari Nagar",
    "Whitefield",
    "Marathahalli",
    "Bellandur",
    "Sarjapur Road",
    "Electronic City",
    "Hebbal",
    "Yelahanka",
    "RT Nagar",
    "Frazer Town",
    "Cox Town",
    "Ulsoor",
    "Domlur",
    "CV Raman Nagar",
    "MG Road Bengaluru",
    "Church Street Bengaluru",
    "Sadashivanagar",
    "Richmond Town",
    "Shivaji Nagar Bengaluru",
    "Kammanahalli",
    "Banaswadi",
    "HRBR Layout",
]
