"""
Two-stage query understanding: NL question -> structured QueryIntent (LLM)
-> Cypher (deterministic Python templating, no LLM).

Splitting these apart does two things:
1. Testable in isolation -- intent-parsing accuracy can be measured against
   a golden set independent of whether the Cypher-building logic is right.
2. Safer -- most query shapes now get their Cypher built by our own template
   code, not freeform-generated by the LLM. The write-keyword blocklist +
   execute_read() in nl_to_cypher.py stay on as defense-in-depth, but they're
   now a backstop, not the primary safety mechanism.
"""

import re
from typing import Literal, Optional

from openai import OpenAI
from pydantic import BaseModel

from graph_schema import get_schema_context

MODEL = "gpt-4o-mini"


def build_fulltext_query(name: str, fuzziness: int = 1) -> str:
    """Turns a name into a Lucene fuzzy query, e.g. "Toitt" -> "Toitt~1" --
    matches within edit distance 1 per token, tolerant of typos without
    being so loose it matches unrelated names. Non-word characters are
    stripped since Lucene treats them as query syntax."""
    tokens = re.findall(r"\w+", name)
    return " ".join(f"{t}~{fuzziness}" for t in tokens)


class QueryIntent(BaseModel):
    category: Optional[str] = None  # must match one of the schema's known Category values, or None
    area: Optional[str] = None  # must match one of the schema's known Area values, or None
    specialty: Optional[str] = None  # must match one of the schema's known Specialty values, or None
    reference_place_name: Optional[str] = None  # a specific named place, for proximity queries
    tier: Optional[Literal["S", "A", "B"]] = None
    relationship: Literal["none", "near_each_other", "near_reference_place", "expand_to_adjacent_areas"] = "none"
    sort_by: Literal["rating", "distance", "none"] = "none"
    limit: int = 10


def build_intent_system_prompt() -> str:
    # Live-introspected, not hand-maintained -- stays accurate as the graph
    # grows (new categories, new areas) without editing this file.
    schema = get_schema_context()
    return f"""You extract structured intent from natural-language questions about Bengaluru food places, for this graph:

{schema}

Extract these fields:
- category: the food/drink category being asked about, if any (must be one of the known categories, or null)
- area: the neighborhood being asked about, if any
- specialty: if the question asks about a specific dish/drink a place is KNOWN FOR (e.g. "good croissants near Toit",
  "places famous for filter coffee in Koramangala", "best biryani spots"), map it to one of the known Specialty
  values above, or null. Don't confuse this with category (broad type of place, e.g. "cafes") -- specialty is
  about what a place is specifically famous for.
- reference_place_name: if the question refers to a SPECIFIC named place (e.g. "near 4P's Pizza", "after visiting X"), extract that name
- tier: "S", "A", or "B" if the question asks about a specific popularity tier, else null
- relationship: which kind of question this is --
  - "near_each_other": asking which places (of a category/area) are close to one another
  - "near_reference_place": asking what's near/after/before a SPECIFIC named place (reference_place_name will be set)
  - "expand_to_adjacent_areas": asking which AREAS are near/adjacent to another area
  - "none": a plain lookup/filter question (top-rated, by category, by area, by tier) with no relationship/proximity aspect
- sort_by: "rating" if the question wants best/top-rated results, "distance" if it wants closest results, else "none"
- limit: how many results make sense (default 10 if unspecified)
"""


def parse_intent(client: OpenAI, question: str, system_prompt: str | None = None) -> QueryIntent:
    # system_prompt is accepted as a param (not always recomputed here) so
    # callers running many questions in a row -- eval_intent.py, the CLI
    # loop -- can introspect the schema once and reuse it, instead of
    # re-querying Neo4j on every single question.
    if system_prompt is None:
        system_prompt = build_intent_system_prompt()

    completion = client.beta.chat.completions.parse(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": question},
        ],
        response_format=QueryIntent,
    )
    return completion.choices[0].message.parsed


def intent_to_cypher(intent: QueryIntent) -> tuple[str, dict]:
    """Returns (cypher, params). Pure Python templating -- no LLM involved."""
    tier_label = f":{intent.tier}" if intent.tier else ""
    params: dict = {"limit": intent.limit}

    if intent.relationship == "near_reference_place" and intent.reference_place_name:
        # Fuzzy full-text lookup (typo/word-order tolerant) instead of exact
        # CONTAINS -- resolves "Toitt" -> "Toit". Tier filters the SUGGESTED
        # places (p), not the reference place itself -- naming a specific
        # place has nothing to do with its own tier.
        params["ref_query"] = build_fulltext_query(intent.reference_place_name)
        category_clause = ""
        if intent.category:
            category_clause = "MATCH (p)-[:IN_CATEGORY]->(:Category {name: $category}) "
            params["category"] = intent.category
        specialty_clause = ""
        if intent.specialty:
            specialty_clause = "MATCH (p)-[:FAMOUS_FOR]->(:Specialty {name: $specialty}) "
            params["specialty"] = intent.specialty
        # sort_by was previously ignored here -- "top-rated near X" and
        # "what's near X" silently ran the identical distance-ordered query.
        order_clause = "ORDER BY p.rating DESC " if intent.sort_by == "rating" else "ORDER BY r.distance_km "
        cypher = (
            "CALL db.index.fulltext.queryNodes('place_name_fulltext', $ref_query) "
            "YIELD node AS ref, score "
            "WITH ref, score ORDER BY score DESC LIMIT 1 "
            f"MATCH (ref)-[r:ADJACENT_TO]-(p:Place{tier_label}) "
            f"{category_clause}{specialty_clause}"
            "RETURN ref.name AS reference, score AS reference_match_confidence, "
            "p.name AS suggestion, p.things_to_try AS things_to_try, r.distance_km AS distance_km "
            + order_clause
            + "LIMIT $limit"
        )
        return cypher, params

    if intent.relationship == "near_each_other":
        area_clause = ""
        category_clause = ""
        if intent.area:
            area_clause = "MATCH (p1)-[:LOCATED_IN]->(:Area {name: $area}) "
            params["area"] = intent.area
        if intent.category:
            category_clause = (
                "MATCH (p1)-[:IN_CATEGORY]->(:Category {name: $category}) "
                "MATCH (p2)-[:IN_CATEGORY]->(:Category {name: $category}) "
            )
            params["category"] = intent.category
        cypher = (
            f"MATCH (p1:Place{tier_label})-[r:ADJACENT_TO]-(p2:Place{tier_label}) "
            f"{area_clause}{category_clause}"
            "RETURN p1.name AS place_a, p2.name AS place_b, r.distance_km AS distance_km "
            "ORDER BY r.distance_km LIMIT $limit"
        )
        return cypher, params

    if intent.relationship == "expand_to_adjacent_areas":
        params["area"] = intent.area
        cypher = (
            "MATCH (:Area {name: $area})-[r:NEAR]-(other:Area) "
            "RETURN other.name AS area, r.distance_km AS distance_km "
            "ORDER BY r.distance_km LIMIT $limit"
        )
        return cypher, params

    # relationship == "none" -- plain filtered lookup
    match_clauses = [f"MATCH (p:Place{tier_label})"]
    if intent.area:
        match_clauses.append("MATCH (p)-[:LOCATED_IN]->(:Area {name: $area})")
        params["area"] = intent.area
    if intent.category:
        match_clauses.append("MATCH (p)-[:IN_CATEGORY]->(:Category {name: $category})")
        params["category"] = intent.category
    if intent.specialty:
        match_clauses.append("MATCH (p)-[:FAMOUS_FOR]->(:Specialty {name: $specialty})")
        params["specialty"] = intent.specialty

    order_clause = ""
    if intent.sort_by == "rating":
        order_clause = "ORDER BY p.rating DESC "

    cypher = (
        " ".join(match_clauses)
        + " RETURN p.name AS name, p.rating AS rating, p.user_rating_count AS user_rating_count, "
        + "p.things_to_try AS things_to_try "
        + order_clause
        + "LIMIT $limit"
    )
    return cypher, params
